version: '3.8'
services:
  bckend:
    build: ./server
    container_name: bckend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: psqlab
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bcknddm
      POSTGRES_HOST: psqlab
      POSTGRES_PORT: 5432
    depends_on:
      - psqlab

  frtend:
    build: ./client
    container_name: frtend
    ports:
      - "80:80"
    depends_on:
      - bckend

  psqlab:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: psqlab
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bcknddm
    ports:
      - "5432:5432"

volumes:
  postgres_data:
