/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoPoint } from './GeoPoint';
import {
    GeoPointFromJSON,
    GeoPointFromJSONTyped,
    GeoPointToJSON,
    GeoPointToJSONTyped,
} from './GeoPoint';

/**
 * tábla a feladatoknak.
 * @export
 * @interface Feladat
 */
export interface Feladat {
    /**
     * egyedi azonosító.
     * @type {number}
     * @memberof Feladat
     */
    readonly fldtId?: number;
    /**
     * rövidnév.
     * @type {string}
     * @memberof Feladat
     */
    rovidnev: string;
    /**
     * részletes leírás.
     * @type {string}
     * @memberof Feladat
     */
    leiras?: string;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Feladat
     */
    readonly letrejott?: Date;
    /**
     * évhónapnaóraperc 00 másodperc.
     * @type {Date}
     * @memberof Feladat
     */
    hatarido?: Date;
    /**
     * GPS koordináta (Point, 4326).
     * @type {GeoPoint}
     * @memberof Feladat
     */
    gpsKoordinata?: GeoPoint | null;
    /**
     * EOV koordináta (Point, 23700).
     * @type {GeoPoint}
     * @memberof Feladat
     */
    eovKoordinata?: GeoPoint | null;
}

/**
 * Check if a given object implements the Feladat interface.
 */
export function instanceOfFeladat(value: object): value is Feladat {
    if (!('rovidnev' in value) || value['rovidnev'] === undefined) return false;
    return true;
}

export function FeladatFromJSON(json: any): Feladat {
    return FeladatFromJSONTyped(json, false);
}

export function FeladatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feladat {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtId': json['fldt_id'] == null ? undefined : json['fldt_id'],
        'rovidnev': json['rovidnev'],
        'leiras': json['leiras'] == null ? undefined : json['leiras'],
        'letrejott': json['letrejott'] == null ? undefined : (new Date(json['letrejott'])),
        'hatarido': json['hatarido'] == null ? undefined : (new Date(json['hatarido'])),
        'gpsKoordinata': json['gps_koordinata'] == null ? undefined : GeoPointFromJSON(json['gps_koordinata']),
        'eovKoordinata': json['eov_koordinata'] == null ? undefined : GeoPointFromJSON(json['eov_koordinata']),
    };
}

export function FeladatToJSON(json: any): Feladat {
    return FeladatToJSONTyped(json, false);
}

export function FeladatToJSONTyped(value?: Omit<Feladat, 'fldt_id'|'letrejott'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rovidnev': value['rovidnev'],
        'leiras': value['leiras'],
        'hatarido': value['hatarido'] == null ? undefined : ((value['hatarido']).toISOString()),
        'gps_koordinata': GeoPointToJSON(value['gpsKoordinata']),
        'eov_koordinata': GeoPointToJSON(value['eovKoordinata']),
    };
}

