/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoPoint } from './GeoPoint';
import {
    GeoPointFromJSON,
    GeoPointFromJSONTyped,
    GeoPointToJSON,
    GeoPointToJSONTyped,
} from './GeoPoint';

/**
 * Feladat adatok létrehozáshoz vagy módosításhoz.
 * @export
 * @interface FeladatInput
 */
export interface FeladatInput {
    /**
     * rövidnév.
     * @type {string}
     * @memberof FeladatInput
     */
    rovidnev: string;
    /**
     * részletes leírás.
     * @type {string}
     * @memberof FeladatInput
     */
    leiras?: string;
    /**
     * évhónapnaóraperc 00 másodperc.
     * @type {Date}
     * @memberof FeladatInput
     */
    hatarido?: Date;
    /**
     * GPS koordináta (Point, 4326).
     * @type {GeoPoint}
     * @memberof FeladatInput
     */
    gpsKoordinata?: GeoPoint | null;
    /**
     * EOV koordináta (Point, 23700).
     * @type {GeoPoint}
     * @memberof FeladatInput
     */
    eovKoordinata?: GeoPoint | null;
}

/**
 * Check if a given object implements the FeladatInput interface.
 */
export function instanceOfFeladatInput(value: object): value is FeladatInput {
    if (!('rovidnev' in value) || value['rovidnev'] === undefined) return false;
    return true;
}

export function FeladatInputFromJSON(json: any): FeladatInput {
    return FeladatInputFromJSONTyped(json, false);
}

export function FeladatInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeladatInput {
    if (json == null) {
        return json;
    }
    return {
        
        'rovidnev': json['rovidnev'],
        'leiras': json['leiras'] == null ? undefined : json['leiras'],
        'hatarido': json['hatarido'] == null ? undefined : (new Date(json['hatarido'])),
        'gpsKoordinata': json['gps_koordinata'] == null ? undefined : GeoPointFromJSON(json['gps_koordinata']),
        'eovKoordinata': json['eov_koordinata'] == null ? undefined : GeoPointFromJSON(json['eov_koordinata']),
    };
}

export function FeladatInputToJSON(json: any): FeladatInput {
    return FeladatInputToJSONTyped(json, false);
}

export function FeladatInputToJSONTyped(value?: FeladatInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rovidnev': value['rovidnev'],
        'leiras': value['leiras'],
        'hatarido': value['hatarido'] == null ? undefined : ((value['hatarido']).toISOString()),
        'gps_koordinata': GeoPointToJSON(value['gpsKoordinata']),
        'eov_koordinata': GeoPointToJSON(value['eovKoordinata']),
    };
}

