/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoPoint } from './GeoPoint';
import {
    GeoPointFromJSON,
    GeoPointFromJSONTyped,
    GeoPointToJSON,
    GeoPointToJSONTyped,
} from './GeoPoint';

/**
 * tábla a feladatokhoz tartozó képeknek.
 * @export
 * @interface Fldtkep
 */
export interface Fldtkep {
    /**
     * egyedi azonosító.
     * @type {number}
     * @memberof Fldtkep
     */
    readonly fldtkepId?: number;
    /**
     * maga a kép base64 kódolással tárolva.
     * @type {string}
     * @memberof Fldtkep
     */
    adat?: string;
    /**
     * kép teljes neve.
     * @type {string}
     * @memberof Fldtkep
     */
    fajlnev: string;
    /**
     * byteban.
     * @type {number}
     * @memberof Fldtkep
     */
    readonly meret?: number;
    /**
     * hozzátartozó leírás.
     * @type {string}
     * @memberof Fldtkep
     */
    leiras?: string;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtkep
     */
    keszult?: Date;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtkep
     */
    readonly letrejott?: Date;
    /**
     * a hely gps koordinátája, ha van (Point, 4326).
     * @type {GeoPoint}
     * @memberof Fldtkep
     */
    gpsKoordinata?: GeoPoint | null;
    /**
     * a hely eov koordinátálya ha van (Point, 23700).
     * @type {GeoPoint}
     * @memberof Fldtkep
     */
    eovKoordinata?: GeoPoint | null;
    /**
     * felhasznló id (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof Fldtkep
     */
    bekuldo: number;
}

/**
 * Check if a given object implements the Fldtkep interface.
 */
export function instanceOfFldtkep(value: object): value is Fldtkep {
    if (!('fajlnev' in value) || value['fajlnev'] === undefined) return false;
    if (!('bekuldo' in value) || value['bekuldo'] === undefined) return false;
    return true;
}

export function FldtkepFromJSON(json: any): Fldtkep {
    return FldtkepFromJSONTyped(json, false);
}

export function FldtkepFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fldtkep {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtkepId': json['fldtkep_id'] == null ? undefined : json['fldtkep_id'],
        'adat': json['adat'] == null ? undefined : json['adat'],
        'fajlnev': json['fajlnev'],
        'meret': json['meret'] == null ? undefined : json['meret'],
        'leiras': json['leiras'] == null ? undefined : json['leiras'],
        'keszult': json['keszult'] == null ? undefined : (new Date(json['keszult'])),
        'letrejott': json['letrejott'] == null ? undefined : (new Date(json['letrejott'])),
        'gpsKoordinata': json['gps_koordinata'] == null ? undefined : GeoPointFromJSON(json['gps_koordinata']),
        'eovKoordinata': json['eov_koordinata'] == null ? undefined : GeoPointFromJSON(json['eov_koordinata']),
        'bekuldo': json['bekuldo'],
    };
}

export function FldtkepToJSON(json: any): Fldtkep {
    return FldtkepToJSONTyped(json, false);
}

export function FldtkepToJSONTyped(value?: Omit<Fldtkep, 'fldtkep_id'|'meret'|'letrejott'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adat': value['adat'],
        'fajlnev': value['fajlnev'],
        'leiras': value['leiras'],
        'keszult': value['keszult'] == null ? undefined : ((value['keszult']).toISOString()),
        'gps_koordinata': GeoPointToJSON(value['gpsKoordinata']),
        'eov_koordinata': GeoPointToJSON(value['eovKoordinata']),
        'bekuldo': value['bekuldo'],
    };
}

