/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * feladat kép összerendelés egy feladat több kép, egy kép több feladat.
 * @export
 * @interface Fldtkp
 */
export interface Fldtkp {
    /**
     * egyedi azonosító.
     * @type {number}
     * @memberof Fldtkp
     */
    readonly fldtkpId?: number;
    /**
     * a feladat azonosítója (referencia Feladat.fldt_id).
     * @type {number}
     * @memberof Fldtkp
     */
    fldtId: number;
    /**
     * a kép azonosítója (referencia Fldtkep.fldtkep_id).
     * @type {number}
     * @memberof Fldtkp
     */
    fldtkepId?: number;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtkp
     */
    readonly letrejott?: Date;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtkp
     */
    readonly modositas?: Date;
}

/**
 * Check if a given object implements the Fldtkp interface.
 */
export function instanceOfFldtkp(value: object): value is Fldtkp {
    if (!('fldtId' in value) || value['fldtId'] === undefined) return false;
    return true;
}

export function FldtkpFromJSON(json: any): Fldtkp {
    return FldtkpFromJSONTyped(json, false);
}

export function FldtkpFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fldtkp {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtkpId': json['fldtkp_id'] == null ? undefined : json['fldtkp_id'],
        'fldtId': json['fldt_id'],
        'fldtkepId': json['fldtkep_id'] == null ? undefined : json['fldtkep_id'],
        'letrejott': json['letrejott'] == null ? undefined : (new Date(json['letrejott'])),
        'modositas': json['modositas'] == null ? undefined : (new Date(json['modositas'])),
    };
}

export function FldtkpToJSON(json: any): Fldtkp {
    return FldtkpToJSONTyped(json, false);
}

export function FldtkpToJSONTyped(value?: Omit<Fldtkp, 'fldtkp_id'|'letrejott'|'modositas'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fldt_id': value['fldtId'],
        'fldtkep_id': value['fldtkepId'],
    };
}

