/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoPoint } from './GeoPoint';
import {
    GeoPointFromJSON,
    GeoPointFromJSONTyped,
    GeoPointToJSON,
    GeoPointToJSONTyped,
} from './GeoPoint';

/**
 * Kép adatok létrehozáshoz vagy módosításhoz.
 * @export
 * @interface FldtkepInput
 */
export interface FldtkepInput {
    /**
     * maga a kép base64 kódolással.
     * @type {string}
     * @memberof FldtkepInput
     */
    adat: string;
    /**
     * kép teljes neve.
     * @type {string}
     * @memberof FldtkepInput
     */
    fajlnev: string;
    /**
     * hozzátartozó leírás.
     * @type {string}
     * @memberof FldtkepInput
     */
    leiras?: string;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof FldtkepInput
     */
    keszult?: Date;
    /**
     * a hely gps koordinátája, ha van (Point, 4326).
     * @type {GeoPoint}
     * @memberof FldtkepInput
     */
    gpsKoordinata?: GeoPoint | null;
    /**
     * a hely eov koordinátálya ha van (Point, 23700).
     * @type {GeoPoint}
     * @memberof FldtkepInput
     */
    eovKoordinata?: GeoPoint | null;
    /**
     * felhasznló id (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof FldtkepInput
     */
    bekuldo: number;
}

/**
 * Check if a given object implements the FldtkepInput interface.
 */
export function instanceOfFldtkepInput(value: object): value is FldtkepInput {
    if (!('adat' in value) || value['adat'] === undefined) return false;
    if (!('fajlnev' in value) || value['fajlnev'] === undefined) return false;
    if (!('bekuldo' in value) || value['bekuldo'] === undefined) return false;
    return true;
}

export function FldtkepInputFromJSON(json: any): FldtkepInput {
    return FldtkepInputFromJSONTyped(json, false);
}

export function FldtkepInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FldtkepInput {
    if (json == null) {
        return json;
    }
    return {
        
        'adat': json['adat'],
        'fajlnev': json['fajlnev'],
        'leiras': json['leiras'] == null ? undefined : json['leiras'],
        'keszult': json['keszult'] == null ? undefined : (new Date(json['keszult'])),
        'gpsKoordinata': json['gps_koordinata'] == null ? undefined : GeoPointFromJSON(json['gps_koordinata']),
        'eovKoordinata': json['eov_koordinata'] == null ? undefined : GeoPointFromJSON(json['eov_koordinata']),
        'bekuldo': json['bekuldo'],
    };
}

export function FldtkepInputToJSON(json: any): FldtkepInput {
    return FldtkepInputToJSONTyped(json, false);
}

export function FldtkepInputToJSONTyped(value?: FldtkepInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adat': value['adat'],
        'fajlnev': value['fajlnev'],
        'leiras': value['leiras'],
        'keszult': value['keszult'] == null ? undefined : ((value['keszult']).toISOString()),
        'gps_koordinata': GeoPointToJSON(value['gpsKoordinata']),
        'eov_koordinata': GeoPointToJSON(value['eovKoordinata']),
        'bekuldo': value['bekuldo'],
    };
}

