/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Feladat megoldás adatok.
 * @export
 * @interface FldtmegoldasInput
 */
export interface FldtmegoldasInput {
    /**
     * megoldas leírása.
     * @type {string}
     * @memberof FldtmegoldasInput
     */
    leiras: string;
    /**
     * felhasznalo azonositó (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof FldtmegoldasInput
     */
    lejelento: number;
    /**
     * igaz, ha el van fogadva.
     * @type {boolean}
     * @memberof FldtmegoldasInput
     */
    elfogadva?: boolean;
    /**
     * elfogado felhasznalo azonositó (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof FldtmegoldasInput
     */
    elfogado?: number | null;
}

/**
 * Check if a given object implements the FldtmegoldasInput interface.
 */
export function instanceOfFldtmegoldasInput(value: object): value is FldtmegoldasInput {
    if (!('leiras' in value) || value['leiras'] === undefined) return false;
    if (!('lejelento' in value) || value['lejelento'] === undefined) return false;
    return true;
}

export function FldtmegoldasInputFromJSON(json: any): FldtmegoldasInput {
    return FldtmegoldasInputFromJSONTyped(json, false);
}

export function FldtmegoldasInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FldtmegoldasInput {
    if (json == null) {
        return json;
    }
    return {
        
        'leiras': json['leiras'],
        'lejelento': json['lejelento'],
        'elfogadva': json['elfogadva'] == null ? undefined : json['elfogadva'],
        'elfogado': json['elfogado'] == null ? undefined : json['elfogado'],
    };
}

export function FldtmegoldasInputToJSON(json: any): FldtmegoldasInput {
    return FldtmegoldasInputToJSONTyped(json, false);
}

export function FldtmegoldasInputToJSONTyped(value?: FldtmegoldasInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leiras': value['leiras'],
        'lejelento': value['lejelento'],
        'elfogadva': value['elfogadva'],
        'elfogado': value['elfogado'],
    };
}

