/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Feladat-Felhasználó összerendelés adatok.
 * @export
 * @interface FldtFlhsznlInput
 */
export interface FldtFlhsznlInput {
    /**
     * feladat azonosító.
     * @type {number}
     * @memberof FldtFlhsznlInput
     */
    fldtId: number;
    /**
     * felhasznalo azonositó.
     * @type {number}
     * @memberof FldtFlhsznlInput
     */
    flhsznlId: number;
    /**
     * egy feladatnál 1 fönök lehet!.
     * @type {boolean}
     * @memberof FldtFlhsznlInput
     */
    fonok: boolean;
}

/**
 * Check if a given object implements the FldtFlhsznlInput interface.
 */
export function instanceOfFldtFlhsznlInput(value: object): value is FldtFlhsznlInput {
    if (!('fldtId' in value) || value['fldtId'] === undefined) return false;
    if (!('flhsznlId' in value) || value['flhsznlId'] === undefined) return false;
    if (!('fonok' in value) || value['fonok'] === undefined) return false;
    return true;
}

export function FldtFlhsznlInputFromJSON(json: any): FldtFlhsznlInput {
    return FldtFlhsznlInputFromJSONTyped(json, false);
}

export function FldtFlhsznlInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FldtFlhsznlInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtId': json['fldt_id'],
        'flhsznlId': json['flhsznl_id'],
        'fonok': json['fonok'],
    };
}

export function FldtFlhsznlInputToJSON(json: any): FldtFlhsznlInput {
    return FldtFlhsznlInputToJSONTyped(json, false);
}

export function FldtFlhsznlInputToJSONTyped(value?: FldtFlhsznlInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fldt_id': value['fldtId'],
        'flhsznl_id': value['flhsznlId'],
        'fonok': value['fonok'],
    };
}

