/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * feladat felhasználó összerendelés.
 * @export
 * @interface FldtFlhsznl
 */
export interface FldtFlhsznl {
    /**
     * egyedi azonosító.
     * @type {number}
     * @memberof FldtFlhsznl
     */
    readonly fldtflhsznlId?: number;
    /**
     * feladat azonosító (referencia Feladat.fldt_id).
     * @type {number}
     * @memberof FldtFlhsznl
     */
    fldtId: number;
    /**
     * felhasznalo azonositó (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof FldtFlhsznl
     */
    flhsznlId: number;
    /**
     * egy feladatnál 1 fönök lehet!.
     * @type {boolean}
     * @memberof FldtFlhsznl
     */
    fonok: boolean;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof FldtFlhsznl
     */
    readonly letrejott?: Date;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof FldtFlhsznl
     */
    readonly modositas?: Date;
}

/**
 * Check if a given object implements the FldtFlhsznl interface.
 */
export function instanceOfFldtFlhsznl(value: object): value is FldtFlhsznl {
    if (!('fldtId' in value) || value['fldtId'] === undefined) return false;
    if (!('flhsznlId' in value) || value['flhsznlId'] === undefined) return false;
    if (!('fonok' in value) || value['fonok'] === undefined) return false;
    return true;
}

export function FldtFlhsznlFromJSON(json: any): FldtFlhsznl {
    return FldtFlhsznlFromJSONTyped(json, false);
}

export function FldtFlhsznlFromJSONTyped(json: any, ignoreDiscriminator: boolean): FldtFlhsznl {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtflhsznlId': json['fldtflhsznl_id'] == null ? undefined : json['fldtflhsznl_id'],
        'fldtId': json['fldt_id'],
        'flhsznlId': json['flhsznl_id'],
        'fonok': json['fonok'],
        'letrejott': json['letrejott'] == null ? undefined : (new Date(json['letrejott'])),
        'modositas': json['modositas'] == null ? undefined : (new Date(json['modositas'])),
    };
}

export function FldtFlhsznlToJSON(json: any): FldtFlhsznl {
    return FldtFlhsznlToJSONTyped(json, false);
}

export function FldtFlhsznlToJSONTyped(value?: Omit<FldtFlhsznl, 'fldtflhsznl_id'|'letrejott'|'modositas'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fldt_id': value['fldtId'],
        'flhsznl_id': value['flhsznlId'],
        'fonok': value['fonok'],
    };
}

