/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * feladatmegoldásokat tartalmazó tábla.
 * @export
 * @interface Fldtmegoldas
 */
export interface Fldtmegoldas {
    /**
     * egyedi azonosító.
     * @type {number}
     * @memberof Fldtmegoldas
     */
    readonly fldtmgldsId?: number;
    /**
     * megoldas leírása.
     * @type {string}
     * @memberof Fldtmegoldas
     */
    leiras: string;
    /**
     * felhasznalo azonositó (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof Fldtmegoldas
     */
    lejelento: number;
    /**
     * igaz, ha el van fogadva.
     * @type {boolean}
     * @memberof Fldtmegoldas
     */
    elfogadva?: boolean;
    /**
     * elfogado felhasznalo azonositó (referencia Felhasznalo.flhsznl_id).
     * @type {number}
     * @memberof Fldtmegoldas
     */
    elfogado?: number | null;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtmegoldas
     */
    readonly letrejott?: Date;
    /**
     * ezredmásodperc pontosság.
     * @type {Date}
     * @memberof Fldtmegoldas
     */
    readonly modositas?: Date;
}

/**
 * Check if a given object implements the Fldtmegoldas interface.
 */
export function instanceOfFldtmegoldas(value: object): value is Fldtmegoldas {
    if (!('leiras' in value) || value['leiras'] === undefined) return false;
    if (!('lejelento' in value) || value['lejelento'] === undefined) return false;
    return true;
}

export function FldtmegoldasFromJSON(json: any): Fldtmegoldas {
    return FldtmegoldasFromJSONTyped(json, false);
}

export function FldtmegoldasFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fldtmegoldas {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtmgldsId': json['fldtmglds_id'] == null ? undefined : json['fldtmglds_id'],
        'leiras': json['leiras'],
        'lejelento': json['lejelento'],
        'elfogadva': json['elfogadva'] == null ? undefined : json['elfogadva'],
        'elfogado': json['elfogado'] == null ? undefined : json['elfogado'],
        'letrejott': json['letrejott'] == null ? undefined : (new Date(json['letrejott'])),
        'modositas': json['modositas'] == null ? undefined : (new Date(json['modositas'])),
    };
}

export function FldtmegoldasToJSON(json: any): Fldtmegoldas {
    return FldtmegoldasToJSONTyped(json, false);
}

export function FldtmegoldasToJSONTyped(value?: Omit<Fldtmegoldas, 'fldtmglds_id'|'letrejott'|'modositas'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leiras': value['leiras'],
        'lejelento': value['lejelento'],
        'elfogadva': value['elfogadva'],
        'elfogado': value['elfogado'],
    };
}

