/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Feladat-Kép összerendelés adatok.
 * @export
 * @interface FldtkpInput
 */
export interface FldtkpInput {
    /**
     * a feladat azonosítója.
     * @type {number}
     * @memberof FldtkpInput
     */
    fldtId: number;
    /**
     * a kép azonosítója.
     * @type {number}
     * @memberof FldtkpInput
     */
    fkepId: number;
}

/**
 * Check if a given object implements the FldtkpInput interface.
 */
export function instanceOfFldtkpInput(value: object): value is FldtkpInput {
    if (!('fldtId' in value) || value['fldtId'] === undefined) return false;
    if (!('fkepId' in value) || value['fkepId'] === undefined) return false;
    return true;
}

export function FldtkpInputFromJSON(json: any): FldtkpInput {
    return FldtkpInputFromJSONTyped(json, false);
}

export function FldtkpInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FldtkpInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fldtId': json['fldt_id'],
        'fkepId': json['fkep_id'],
    };
}

export function FldtkpInputToJSON(json: any): FldtkpInput {
    return FldtkpInputToJSONTyped(json, false);
}

export function FldtkpInputToJSONTyped(value?: FldtkpInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fldt_id': value['fldtId'],
        'fkep_id': value['fkepId'],
    };
}

