/* tslint:disable */
/* eslint-disable */
/**
 * Bcknddm API
 * API a bcknddm adatbázis tábláinak kezeléséhez. Generálva a backnddbcreate.sql alapján.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luczialex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUser200Response
 */
export interface LoginUser200Response {
    /**
     * A felhasználó API kulcsa, amit a további hívásokhoz használni kell.
     * @type {string}
     * @memberof LoginUser200Response
     */
    apikulcs?: string;
}

/**
 * Check if a given object implements the LoginUser200Response interface.
 */
export function instanceOfLoginUser200Response(value: object): value is LoginUser200Response {
    return true;
}

export function LoginUser200ResponseFromJSON(json: any): LoginUser200Response {
    return LoginUser200ResponseFromJSONTyped(json, false);
}

export function LoginUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'apikulcs': json['apikulcs'] == null ? undefined : json['apikulcs'],
    };
}

export function LoginUser200ResponseToJSON(json: any): LoginUser200Response {
    return LoginUser200ResponseToJSONTyped(json, false);
}

export function LoginUser200ResponseToJSONTyped(value?: LoginUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apikulcs': value['apikulcs'],
    };
}

